-- Sanitized sample from an internal infrastructure monitoring project.
-- Secrets, internal identifiers, and localized text have been removed or generalized.

-- IDENTITY_GOVERNANCE, EMS, EMSPREMIUM, AAD_PREMIUM, AAD_PREMIUM_P2, MCOPSTNC, MCOPSTN2,
-- POWERAPPS_PER_APP, POWERAPPS_PER_USER, PROJECT_PLAN_1, PROJECT_PLAN_3, VISIO_PLAN1, VISIO_PLAN2,
-- DEFENDER_ENDPOINT_P1, DEFENDER_ENDPOINT_P2, DEFENDER_IDENTITY, DEFENDER_OFFICE365_P1, DEFENDER_OFFICE365_P2,
-- INTUNE_A, INTUNE_SUITE, M365_COPILOT, COPILOT_STANDARD

IF OBJECT_ID(N'fact.M365LicenseCostByDepartment', N'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'ENTERPRISEPREMIUM')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [ENTERPRISEPREMIUM] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'M365_E3')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [M365_E3] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'M365_E5')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [M365_E5] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'M365_E5_SECURITY')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [M365_E5_SECURITY] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'M365_E5_COMPLIANCE')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [M365_E5_COMPLIANCE] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'IDENTITY_GOVERNANCE')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [IDENTITY_GOVERNANCE] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'EMS')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [EMS] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'EMSPREMIUM')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [EMSPREMIUM] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'AAD_PREMIUM')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [AAD_PREMIUM] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'AAD_PREMIUM_P2')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [AAD_PREMIUM_P2] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'MCOPSTNC')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [MCOPSTNC] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'MCOPSTN2')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [MCOPSTN2] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'POWERAPPS_PER_APP')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [POWERAPPS_PER_APP] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'POWERAPPS_PER_USER')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [POWERAPPS_PER_USER] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'PROJECT_PLAN_1')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [PROJECT_PLAN_1] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'PROJECT_PLAN_3')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [PROJECT_PLAN_3] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'VISIO_PLAN1')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [VISIO_PLAN1] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'VISIO_PLAN2')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [VISIO_PLAN2] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'DEFENDER_ENDPOINT_P1')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [DEFENDER_ENDPOINT_P1] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'DEFENDER_ENDPOINT_P2')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [DEFENDER_ENDPOINT_P2] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'DEFENDER_IDENTITY')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [DEFENDER_IDENTITY] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'DEFENDER_OFFICE365_P1')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [DEFENDER_OFFICE365_P1] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'DEFENDER_OFFICE365_P2')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [DEFENDER_OFFICE365_P2] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'INTUNE_A')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [INTUNE_A] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'INTUNE_SUITE')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [INTUNE_SUITE] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'M365_COPILOT')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [M365_COPILOT] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'COPILOT_STANDARD')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [COPILOT_STANDARD] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'THREAT_INTELLIGENCE')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [THREAT_INTELLIGENCE] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'EXCHANGESTANDARD')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [EXCHANGESTANDARD] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'Microsoft_Teams_Premium')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [Microsoft_Teams_Premium] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'Microsoft_Teams_Exploratory_Dept')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [Microsoft_Teams_Exploratory_Dept] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'POWER_BI_STANDARD')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [POWER_BI_STANDARD] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'PBI_PREMIUM_PER_USER')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [PBI_PREMIUM_PER_USER] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'TEAMS_ESSENTIALS_AAD')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [TEAMS_ESSENTIALS_AAD] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'PROJECTPROFESSIONAL')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [PROJECTPROFESSIONAL] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'POWERAUTOMATE_ATTENDED_RPA')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [POWERAUTOMATE_ATTENDED_RPA] INT NOT NULL DEFAULT 0;
    
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'fact' AND TABLE_NAME = 'M365LicenseCostByDepartment' AND COLUMN_NAME = 'Microsoft_365_Copilot')
        ALTER TABLE [fact].[M365LicenseCostByDepartment] ADD [Microsoft_365_Copilot] INT NOT NULL DEFAULT 0;
    
    PRINT 'Sanitized label';
END
ELSE
BEGIN
    PRINT 'Sanitized label';
END
GO

